name: proyecto_gym
description: "A new Flutter project."

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_datetime_picker_plus: ^2.2.0
  provider: ^6.1.2
  fluttertoast: ^8.2.12
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1

  flutter:
    sdk: flutter
  intl: ^0.20.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/