name: proyecto_gym
description: "A new Flutter project."

publish_to: "none"

version: 3.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter_datetime_picker_plus: ^2.2.0
  flutter_local_notifications: ^19.0.0
  provider: ^6.1.3
  fluttertoast: ^8.2.12
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
