// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJt43M_Nl-CzruScXCT1Fpt0_q0yr4ZD4',
    appId: '1:218794199665:web:e3c9efef4e8da1d09fa9d0',
    messagingSenderId: '218794199665',
    projectId: 'registergym-6c598',
    authDomain: 'registergym-6c598.firebaseapp.com',
    storageBucket: 'registergym-6c598.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwtM4_s-t2BKYqooU_eo9WC4tYiFf7D1c',
    appId: '1:218794199665:android:21f1fcf344e3aa249fa9d0',
    messagingSenderId: '218794199665',
    projectId: 'registergym-6c598',
    storageBucket: 'registergym-6c598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwboFzXyhxz2-HYKxr4SPCOJ9pKolvZZw',
    appId: '1:218794199665:ios:4255965bea10a52f9fa9d0',
    messagingSenderId: '218794199665',
    projectId: 'registergym-6c598',
    storageBucket: 'registergym-6c598.firebasestorage.app',
    iosBundleId: 'com.example.proyectoGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwboFzXyhxz2-HYKxr4SPCOJ9pKolvZZw',
    appId: '1:218794199665:ios:4255965bea10a52f9fa9d0',
    messagingSenderId: '218794199665',
    projectId: 'registergym-6c598',
    storageBucket: 'registergym-6c598.firebasestorage.app',
    iosBundleId: 'com.example.proyectoGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJt43M_Nl-CzruScXCT1Fpt0_q0yr4ZD4',
    appId: '1:218794199665:web:77df32261c861a9d9fa9d0',
    messagingSenderId: '218794199665',
    projectId: 'registergym-6c598',
    authDomain: 'registergym-6c598.firebaseapp.com',
    storageBucket: 'registergym-6c598.firebasestorage.app',
  );
}
